### ISSUE TITLE
http.client.RemoteDisconnected: Remote end closed connection without response

### ISSUE THREAD

**Issue by hongsheng-Z** [ssundaram21/dreamsim#11]
Thanks for your great work, but there is something wrong when I use the "from dreamsim import dreamsim" to evaluate my Dataset! The terminator shows  "Downloading checkpoint", and the wrong " raise RemoteDisconnected("Remote end closed connection without")  http.client.RemoteDisconnected: Remote end closed connection without response" has occurred after a few minutes! I'd like to know how to fix this. Thanks.

**Comment by ssundaram21** [comment]
Hi - sorry that you're having this issue! Happy to look into this. Can you provide some more details:
1) Which version of the package you're using.
2) What was the exact command that you used to instantiate the model (i.e. `model, preprocess = dreamsim(...)`) and what the exact output was. It sometimes downloads multiple checkpoints, so it's helpful to know which exact one(s) it failed on.

I jalso ust tested locally and on [our colab](https://colab.research.google.com/drive/1taEOMzFE9g81D9AwH27Uhy2U82tQGAVI?usp=sharing#scrollTo=Su1qEoIl_RML) and didn't run into any issues there, but not sure what your exact usage was.

**Comment by hongsheng-Z** [comment]
Thanks for your reply. My code looks as follows:

from dreamsim import dreamsim
from PIL import Image

dsim_model, process = dreamsim(pretrained=True)
img1 = process(Image.open('input.png')).to('cuda')
img2 = process(Image.open('gt.png')).to('cuda')
distance = dsim_model(img1, img2)
print(distance)

**Comment by stephanie-fu** [comment]
I can't seem to reproduce this issue either, and the error might imply no response on the server-side... could you try using `torch.hub` to download some other weights, like DINO/CLIP separately or ResNet so we can see if this is specific to DreamSim?

Also, could you paste the entire stack trace for this error? Thanks for your patience!

**Comment by hongsheng-Z** [comment]
Ok, thanks! I've solved it, I think it was caused by my network and I solved it after several attempts. However, when I use "dsim_model, process = dreamsim(pretrained=True)" to calculate Dreamsim, I get a very small value (=0.0129), even though the two images look very different, is this a normal value?

**Comment by ssundaram21** [comment]
Happy to take a look at this. Is there any way that you can share the images so that we can reproduce? 

Generally that is quite small for a DreamSim output value, so I wouldn't expect to see that for images that are very visually different. For some examples see [our Colab](https://colab.research.google.com/drive/1taEOMzFE9g81D9AwH27Uhy2U82tQGAVI)

**Comment by stephanie-fu** [comment]
Closing this, but feel free to re-open if you experience further issues!
