### ISSUE TITLE
Support for PEFT > 0.1.0

### ISSUE THREAD

**Issue by Clement-Lelievre** [ssundaram21/dreamsim#12]
**Support for PEFT > 0.1.0 planned?**

**System Info**
peft==0.7.0 (also tried with all versions from 0.2.0 to the current latest peft-0.7.2.dev0)
accelerate==0.25.0
transformers==4.36.1

Python 3.10.12
CUDA Version: 12.2
Ubuntu 20.04.6

_dreamsim==0.1.3_

We are trying to use dreamsim with the newest PEFT backend.
From PEFT we know that:

              There is no direct support for loading those old adapters. One thing you could do which may work: Download the repo to a  local folder, edit the `adapter_config.json` and remove the line `"enable_lora": null,`, then try to load the model from your local folder instead of from HF. If that works, you can create your own HF repo and upload the "fixed" version there for the future.

_Originally posted by @BenjaminBossan in https://github.com/huggingface/peft/issues/1087#issuecomment-1798527118_
            

**MRE**

```python
from dreamsim import dreamsim

dreamsim()
```

results in the below error:

```
/home/ubuntu/anaconda3/envs/train/lib/python3.10/site-packages/torch/nn/utils/weight_norm.py:30: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
  warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")
Traceback (most recent call last):
  File "/home/ubuntu/Developments/github.com/scenario-labs/phoenix/toto.py", line 3, in <module>
    dreamsim()
  File "/home/ubuntu/anaconda3/envs/train/lib/python3.10/site-packages/dreamsim/model.py", line 225, in dreamsim
    extractor.model = PeftModel.from_pretrained(extractor.model, load_dir).to(device)
  File "/home/ubuntu/anaconda3/envs/train/lib/python3.10/site-packages/peft/peft_model.py", line 323, in from_pretrained
    config = PEFT_TYPE_TO_CONFIG_MAPPING[
  File "/home/ubuntu/anaconda3/envs/train/lib/python3.10/site-packages/peft/config.py", line 137, in from_pretrained
    config = config_cls(**kwargs)
TypeError: LoraConfig.__init__() got an unexpected keyword argument 'enable_lora'
```

The above proposed fix does not work for us; locating `adapter_config.json` and dropping the `enable_lora` data produces the same error, this time with the key `merge_weights `. Dropping this key leads to a shape mismatch error.

**Expected behavior**

Model weights should load.

**Comment by stephanie-fu** [comment]
Hi there, thanks for the heads up! We're looking into using a newer version of PEFT and will update this issue with progress.

**Comment by Clement-Lelievre** [comment]
Thanks @stephanie-fu 
Looking forward to using the updated version!

**Comment by Clement-Lelievre** [comment]
Hi @stephanie-fu 

catching up on this topic :)

**Comment by Correr-Zhou** [comment]
Hi authors,

I also suffer from this error about "LoRAConfig". : (

Hope the updated version will be coming soon.

Thanks for your time and effort.

**Comment by Correr-Zhou** [comment]
Hi @stephanie-fu, could you please help with this?

**Comment by ssundaram21** [comment]
Hi -- happy to announce that this has been addressed in our new release! Please do the following:
- Update the pip package to version 0.2.0
- Update to `peft >= 0.2.0`
- Delete any local/cached checkpoints

On the next run, it should automatically download the new checkpoints. 

Please let us know if you have any issues with the new version/checkpoints.

**Comment by Correr-Zhou** [comment]
Thank you very much! I will try this.

> Hi -- happy to announce that this has been addressed in our new release! Please do the following:
> 
> * Update the pip package to version 0.2.0
> * Update to `peft >= 0.2.0`
> * Delete any local/cached checkpoints
> 
> On the next run, it should automatically download the new checkpoints.
> 
> Please let us know if you have any issues with the new version/checkpoints.

**Comment by BenjaminBossan** [comment]
When you get this type of error, it means that the checkpoint is from a later version of PEFT than the one you're using. You have 2 options:

1. Upgrade PEFT to a later version.
2. Manually edit the `adapter_config.json` and remove all items that are not recognized, in this instance `layer_replication`.

**Comment by ssundaram21** [comment]
Interesting -- we'll update the peft version requirements to reflect this. Apologies!
