### ISSUE TITLE
how to load the model after fine-tuning lora

### ISSUE THREAD

**Issue by learn01one** [ssundaram21/dreamsim#14]
Hello, how to load the model after fine-tuning lora? replace clip_vitb16_lora, dino_vitb16_lora, open_clip_vitb16_lora in the models folder? There is a ckpt file after fine-tuning. I don’t know how to use it.

**Comment by stephanie-fu** [comment]
Hi, if you are doing some fine-tuning on your own, the lora weights are saved in folders named `epoch_{n}_{backbone}`. We have some loading code for these lora weights at https://github.com/ssundaram21/dreamsim/blob/main/training/train.py#L199 . You should be able to pull out this code snippet and point it to your checkpoint locations, but let us know if you run into any more issues!
