### ISSUE TITLE
 is it possible to fine-tune all parameters of the network?

### ISSUE THREAD

**Issue by learn01one** [ssundaram21/dreamsim#15]
Hello, is it possible to fine-tune all parameters of the network?

**Comment by stephanie-fu** [comment]
Hi, yes it's possible to full fine-tune all parameters or to use another fine-tuning scheme! We set up linear or lora tuning here: https://github.com/ssundaram21/dreamsim/blob/main/training/train.py#L107 but if you skip this and instead unfreeze all the weights, you will be able to fine-tune everything. 

Just a note: we initially tried full fine-tuning but found it to be more finicky and did not reach as high of an accuracy, so you may need to train more carefully before seeing returns :)
