### ISSUE TITLE
Issues with downloading the dataset

### ISSUE THREAD

**Issue by atharvadeore999** [ssundaram21/dreamsim#17]
When i try to download the dataset , the download gets cancelled on its own after some time  causing incomplete download.Please help with this , or let me know any other alternative to download the dataset.

**Comment by imneonizer** [comment]
I use this free tool for downloading large files https://xtremedownloadmanager.com it comes with parallel downloading and fault tolerance capabilities.

**Comment by Adenialzz** [comment]
Can you upload the dataset to google drive for easier download ? Thanks @ssundaram21

**Comment by atharvadeore999** [comment]
You can download it using xtreme download manager as mentioned by @imneonizer it works
