### ISSUE TITLE
l14 model?

### ISSUE THREAD

**Issue by PerrinAntonin** [ssundaram21/dreamsim#2]
Hello, I've tested your method and I find it really interesting! I've tried it on my data and the performance gains are quite significant compared to an openclip model alone.
I understood that the dreamsim "demo" on github was based on dino_vitb16, clip_vitb16, open_clip_vitb16 and I wanted to know if it was possible to run it on a larger model? I understood that there were l14 models available, do you just need to modify the config file to use them?

**Comment by ssundaram21** [comment]
Hi - that's great to hear. 

Our DreamSim model uses concatenated embeddings from {dino_vitb16, clip_vitb16, open_clip_vitb16}, finetuned on our dataset. We don't have finetuned checkpoints that use l14, but you can initialize a baseline (non-finetuned) model with l14 using the `PerceptualModel` class and swapping out the `model_type` argument.
```
model = PerceptualModel(
      feat_type='cls,embedding,embedding', 
      model_type='dino_vitb16,clip_vitb16,open_clip_vitl14', 
      stride='16,32,14', 
      baseline=True)
```
If you want to finetune this on our dataset, you can follow the readme instructions for running training and would just have to modify the model_type argument in [configs/train_ensemble_model_lora.yaml](https://github.com/ssundaram21/dreamsim/blob/ddf4beb34c4ef7814b75fe901ff26a5aa06ba6aa/configs/train_ensemble_model_lora.yaml). We just pushed a fix involving loading the l14 model so you might have to pull and re-run `download_models.sh` before training. 

Hope this helps and please follow-up if you run into any issues!

**Comment by PerrinAntonin** [comment]
Hello! thank you for your reply! I'll try to see if I can do some training. I was also wondering what models you used, are they the pre-trainings done on laion db on hugging face (for openclip for example)?

**Comment by stephanie-fu** [comment]
Hi there,

Yes, our openclip baseline model is the one pretrained on LAION-400M (and DINO on imagenet, CLIP on online data). Best of luck with your training!
