### ISSUE TITLE
Training Error

### ISSUE THREAD

**Issue by imneonizer** [ssundaram21/dreamsim#25]
I am trying to train on NIGHTS dataset, since exact versions are not mentioned in `requirements.txt` I am using the latest available version.

It would be helpful to know what exact versions you are using for training.

```
Traceback (most recent call last):
  File "/mnt/raid0/nitin/dreamsim/training/train.py", line 290, in <module>
    run(args, device)
  File "/mnt/raid0/nitin/dreamsim/training/train.py", line 276, in run
    model = LightningPerceptualModel(device=device, train_data_len=len(train_dataset), **vars(args))
  File "/mnt/raid0/nitin/dreamsim/training/train.py", line 102, in __init__
    self.__prep_lora_model()
  File "/mnt/raid0/nitin/dreamsim/training/train.py", line 213, in __prep_lora_model
    self.perceptual_model = get_peft_model(self.perceptual_model, config)
  File "/usr/local/lib/python3.10/dist-packages/peft/mapping.py", line 136, in get_peft_model
    model_config = model.config.to_dict()
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1728, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'PerceptualModel' object has no attribute 'config'

```

**Comment by atharvadeore999** [comment]
Which dreamsim version are you using ?
Please check whether you are giving  correct config file path in the argument.
You should have this code at line 212 : config = LoraConfig(
            r=self.lora_r,
            lora_alpha=self.lora_alpha,
            lora_dropout=self.lora_dropout,
            bias='none',
            target_modules=['qkv']
        )

**Comment by imneonizer** [comment]
I found it to be `dreamsim==0.1.3` probably from a previous installation.  
Just found out that pypi has `dreamsim==0.2.1` will try again.

**Comment by imneonizer** [comment]
Thanks, I got the training working! Hopefully if everything works out, I will be able to put a tutorial on YT regarding training with custom dataset.

**Comment by atharvadeore999** [comment]
Great to hear that . Best of luck.
