### ISSUE TITLE
Custom training

### ISSUE THREAD

**Issue by PerrinAntonin** [ssundaram21/dreamsim#4]
Hello, I recently did a training with the following models dino_vitb8,clip_vitl14,open_clip_vitl14. However, I did this training on the night dataset. Do you think it would be useful to do a finetuning on a custom dataset, with more traditional data? In other words, the reference image corresponds to one class, the image on the right is another image from the same class and the image on the left corresponds to an image from another class.

**Comment by ssundaram21** [comment]
Hello,

We haven't tried that particular idea, but would be interested to see what the results are like! It sounds like the learning objective in this case would be different from training on NIGHTS, where we aim to learn mid-level visual similarity. My intuition is that if the classes are more coarse-grained with visually hard negatives then the model might learn more conceptual/semantic information, and if they're finegrained it might pick up on visual similarities. An interesting corner case would be if the image from the other class is actually more visually similar (potential example - the middle image is a husky, the same-class image is a chihuahua, and the other-class image is a wolf).

**Comment by PerrinAntonin** [comment]
Thank you for your reply, it's a very interesting point you raise, I have a few similar classes where this could happen and where problems are currently appearing. I also had a question about the evaluation script, I get 2 results: 

```
INFO:root:Evaluating NIGHTS dataset.
INFO:root:2AFC score: tensor([0.9712], device='cuda:0')
INFO:root:Evaluating NIGHTS dataset.
INFO:root:2AFC score: tensor([0.9655], device='cuda:0')
INFO:root:Combined 2AFC score: 0.9687499667664892
```

Is this just an average over two evaluations with different initialisation or is there another explanation for why two evaluations are done on the same dataset?

**Comment by stephanie-fu** [comment]
Hi there! The two results you're seeing are on the subset of NIGHTS generated with and without ImageNet labels, respectively (we did this to evaluate how well backbones trained on ImageNet (e.g. DINO) would do on non-ImageNet-based data).

The combined score is a weighted average of the two, and in most cases is the one that actually matters for evaluation. You can check out how we do the evaluations here: https://github.com/ssundaram21/dreamsim/blob/main/training/evaluate.py#L192

**Comment by PerrinAntonin** [comment]
Ok ok perfect, Thanks!
