### ISSUE TITLE
Interpolation method  in preprocessing

### ISSUE THREAD

**Issue by worthaglimpse** [ssundaram21/dreamsim#6]
The preprocess function uses bicubic interpolation to resize images to (224,224). How big of a difference in performance will it make if we change it to bilinear or inter-area ? Have you done any experiment on this ? Just curious to find out.

**Comment by Netanel-Tamir** [comment]
Hi, 
We haven't tried using those interpolation methods. We use bicubic to be consistent with the original preprocessing functions of the different foundation models.
However you're more than welcome to try it out and let us know how it affects the performance.
