### ISSUE TITLE
JND dataset

### ISSUE THREAD

**Issue by SaraGhazanfari** [ssundaram21/dreamsim#7]
Hi,

I have a question and appreciate your answer.
As you mentioned in the paper the night dataset has JND labels. I couldn't find the JND labels in the night dataset.
Also, the JND values are reported in the paper but the part of the code to calculate JND values is also missing.

Could you help with this?

Thanks

**Comment by stephanie-fu** [comment]
Hi there! We haven't released the JND labels, and they aren't necessary for training on NIGHTS (which is labeled with 2AFC judgments). We will work on releasing JND data soon, however!

**Comment by HarshitGupta29** [comment]
Any updates ?

**Comment by ssundaram21** [comment]
Hi, happy to update that we have released the JND labels in our latest release! You can now download the just-noticeable difference (JND) votes by running `dataset/download_jnd_dataset.sh`. The CSV will be downloaded to ./dataset/jnd_votes.csv. Check out the [Colab](https://colab.research.google.com/drive/1taEOMzFE9g81D9AwH27Uhy2U82tQGAVI?usp=sharing) for an example of loading a JND trial.
