### ISSUE TITLE
dreamsim onnx model?

### ISSUE THREAD

**Issue by imneonizer** [ssundaram21/dreamsim#9]
Hello,
Thank you for the great work, I have been testing various image embedding models with my custom evaluation data and code to for top-1 ranking. I have been using `fashion_clip` which worked just fine but dreamsim accuracy is on a whole another level.

As I see the source code, based on different parameters a lot of architecture changes and model parameter modification is done also it downloads multiple model weight files even if I only want to use a single branch `dino_vitb16` model.

Is it possible to merged the weights as a single model or possibility to export this single branch model as onnx, that would really boost the production deployment or help create simpler inference pipelines.

Here is a plot about accuracy of different embedding models on my data:
![image](https://github.com/ssundaram21/dreamsim/assets/13932346/57fe08eb-0305-4698-88fe-9a63a78b667a)

**Comment by stephanie-fu** [comment]
Hi there, glad to hear that the model has been helpful! Merging the weights sounds like a great idea, as the full model can be heavy for some applications. This is something we'll consider for the future.
